import { promises as fs } from 'fs'
import os from 'os'
import path from 'path'
import {
  ELEVENLABS_STS_MODEL,
  ELEVENLABS_TTS_MODEL,
  sanitizeWords,
  type WordTiming,
} from '@shared/domain'
import type { ProviderVoice } from '@shared/ipc'
import {
  MOCK_SAMPLE_RATE,
  MOCK_TEXT_TAG,
  layoutWords,
  mockDuration,
  mockUsage,
  parseFfmetadata,
  synthesizeMock,
} from '@shared/mock-voice'
import type { ProviderModel } from '@shared/provider-models'
import { ffmpegStderr, parseProbe, runFfmpeg } from '../ffmpeg'
import type { TtsRequest } from './elevenlabs'
import type { VoiceProvider } from './voice-provider'

type AudioRequest = { audio: Buffer; filename: string }

const MP3_ARGS = [
  '-map_metadata', '-1',
  '-fflags', '+bitexact',
  '-flags:a', '+bitexact',
  '-ac', '1',
  '-ar', String(MOCK_SAMPLE_RATE),
  '-c:a', 'libmp3lame',
  '-b:a', '128k',
]

const MOCK_VOICES: ProviderVoice[] = [
  { id: 'mock-alto', name: 'Mock Alto' },
  { id: 'mock-bass', name: 'Mock Bass' },
  { id: 'mock-tenor', name: 'Mock Tenor' },
]

const MOCK_MODEL = { style: true, boost: true, languages: [], costMultiplier: 1 }

const MOCK_MODELS: ProviderModel[] = [
  { ...MOCK_MODEL, id: ELEVENLABS_TTS_MODEL, name: 'Mock Multilingual', tts: true, sts: false },
  { ...MOCK_MODEL, id: ELEVENLABS_STS_MODEL, name: 'Mock Speech to Speech', tts: false, sts: true },
]

let used = 0

async function inTemp<T>(fn: (dir: string) => Promise<T>): Promise<T> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'vostudio-mock-'))
  try {
    return await fn(dir)
  } finally {
    await fs.rm(dir, { recursive: true, force: true })
  }
}

async function speak(req: TtsRequest): Promise<{ audio: Buffer; words: WordTiming[] }> {
  const text = req.text.trim()
  const duration = mockDuration(text, req.settings.speed)
  const words = layoutWords(text, duration)
  const samples = synthesizeMock(words, duration, req.voiceId)
  const audio = await inTemp(async (dir) => {
    const raw = path.join(dir, 'speech.f32')
    const out = path.join(dir, 'speech.mp3')
    await fs.writeFile(raw, new Uint8Array(samples.buffer))
    await runFfmpeg([
      '-f', 'f32le', '-ar', String(MOCK_SAMPLE_RATE), '-ac', '1', '-i', raw,
      ...MP3_ARGS,
      ...(text ? ['-metadata', `${MOCK_TEXT_TAG}=${text}`] : []),
      out,
    ])
    return fs.readFile(out)
  })
  used += text.length
  return { audio, words }
}

const inputFile = (dir: string, req: AudioRequest): string =>
  path.join(dir, `input${path.extname(req.filename)}`)

const reencode = (req: AudioRequest): Promise<Buffer> =>
  inTemp(async (dir) => {
    const input = inputFile(dir, req)
    const out = path.join(dir, 'output.mp3')
    await fs.writeFile(input, req.audio)
    await runFfmpeg(['-i', input, ...MP3_ARGS, out])
    return fs.readFile(out)
  })

const transcript = (req: AudioRequest): Promise<{ text: string; duration: number }> =>
  inTemp(async (dir) => {
    const input = inputFile(dir, req)
    const meta = path.join(dir, 'meta.txt')
    await fs.writeFile(input, req.audio)
    const stderr = await ffmpegStderr(['-i', input, '-f', 'ffmetadata', meta])
    const text = (parseFfmetadata(await fs.readFile(meta, 'utf8'))[MOCK_TEXT_TAG] ?? '').trim()
    if (!text) throw new Error('Mock transcription only reads audio generated by the mock voice')
    return { text, duration: parseProbe(stderr).duration ?? 0 }
  })

export const mockProvider: VoiceProvider = {
  id: 'mock',
  hasApiKey: async () => true,
  tts: async (req) => (await speak(req)).audio,
  ttsWithTimestamps: async (req) => {
    const { audio, words } = await speak(req)
    const timed = sanitizeWords(words)
    return timed ? { audio, words: timed } : { audio }
  },
  sts: reencode,
  audioIsolation: reencode,
  stt: async (req) => (await transcript(req)).text,
  sttWords: async (req) => {
    const { text, duration } = await transcript(req)
    return layoutWords(text, duration)
  },
  voices: async () => MOCK_VOICES,
  models: async () => MOCK_MODELS,
  usage: async () => mockUsage(used),
}
